# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc633ca966c5281de0c6652f0c52f9e0c14968b4a758d6732b83a236213513448f0a4548a38652db9f172f1659dc29ba7773d84420aff05e50c61262bbfe50ff

test:
  secret_key_base: 34a752f6b0dd1fe36531a45dd7856efcd5d58140d237b8dffa2d44d743d9f141c03937ad4548cb347066d14175b90af04199f59783aa02483247ccf3ac80d185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
